// eslint-disable-next-line import/no-unresolved
import { Strings } from '../strings';

export const english: Strings = {
  general: {
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    details: 'Details',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    submit: 'Submit',
  },
  terms: {
    open_positions: 'Open Positions',
    last_open_position_date: 'Last Open Position Date',
    open_position_volume: 'Open Positions Volume',
    open_position_lots: 'Open Positions Lots',
    open_position_spread: 'Open Positions Spread',
    closed_positions: 'Closed Positions',
    closed_positiont_volume: 'Closed Positions Volume',
    closed_positiont_lots: 'Closed Positions Lots',
    closed_position_spread: 'Closed Positions Spread',
    unique_clicks: 'Unique Clicks',
    leads: 'Leads',
    registrations: 'Registrations',
    conversion_rate: 'Conversion Rate',
    ftd: 'FTD',
    qftd: 'QFTD',
    roi: 'ROI',
    impressions: 'Impressions',
    clicks: 'Clicks',
    ctr: 'CTR',
    unique_click: 'Unique Click',
    commission: 'Commission',
    installations: 'Installations',
    first_deposit: 'First Deposit',
    first_deposit_date: 'First Deposit Date',
    net_deposits: 'Net Deposits',
    visitors: 'Visitors',
    afp: 'AFP',
    unique_visitors: 'Unique Visitors',
    unique_leads: 'Unique Leads',
    unique_registrations: 'Unique Registrations',
    demo: 'Demo',
    unique_demo: 'Unique Demo',
    volume: 'Volume',
    deposits: 'Deposits',
    status: 'Status',
    qualification_date: 'Qualification Date',
    country: 'Country',
    pl: 'PL',
    net_pl: 'Net PL',
    deposit_count: 'Deposit Count',
    total_deposits: 'Total Deposits',
    commissions: 'Commissions',
    commission_count: 'Commission Count',
    earned: 'Earned',
    unique_impressions: 'Unique Impressions',
    position_count: 'Position Count',
    lot_amount: 'Lot Amount',
    fdd: '@:terms.first_deposit_date',
    total_bonus: 'Total Bonus',
    withdrawals: 'Withdrawals',
    generic_string1: '@:reports.columns.generic1',
    generic_string2: '@:reports.columns.generic2',
    generic_string3: '@:reports.columns.generic3',
    position_id: 'Position ID',
    customer_name: 'Customer Name',
  },
  commissions: {
    revshare_enabled_countries: 'Revshare Enabled Countries',
    unified_plan: 'Unified Plan',
    commission_plan: 'Commission Plan',
    active_plan: 'Active Plan',
    commission_cut: 'Commission Cut',
    rev_share: 'Rev Share',
    spread_rev_share_per_symbol: 'Spread Revshare Per Symbol',
    lot_rev_share_per_symbol: 'Lot Revshare Per Symbol',
    brokerage_fee_rev_share_per_symbol: 'Brokerage Fee Revshare Per Symbol',
    point_per_lot_revshare: 'Point Per Lot Revshare',
    ngr_revshare_by_country: 'NGR Revshare By Country',
    position_volume_revshare: 'Position Volume Revshare',
    cpa: 'CPA',
    cpa_amount: 'CPA Amount',
    cpl: 'CPL',
    pcpl: 'Premium CPL',
    cpi: 'CPI',
    sub_affiliate: 'Sub-Affiliate',
    cpaa: 'CPAA',
    bonus: 'Bonus',
    fixed_cpa: 'Fixed CPA',
    cpa_by_country: 'CPA by Country',
    cpa_by_product: 'CPA by Product',
    first_deposit_cpa: 'First Deposit CPA',
    first_deposit_cpa_limit: 'First Deposit CPA Limit',
    ftd_tiers: 'FTD Tiers',
    progressive_cpa_tiers: 'Progressive CPA Tiers',
    traders_tiers: 'Traders Tiers',
    trader_tiers: '@:commissions.traders_tiers',
    net_pl: 'Lifetime Net PL',
    monthly_net_deposits_tiers: 'Monthly Net Deposits Tiers',
    monthly_pl_tiers: 'Monthly PL Tiers',
    tier_x: 'Tier {{x}}',
    between_x_to_y: 'Between {{x}} to {{y}}',
    net_deposit: 'Lifetime Net Deposit',
    commission_per_lot: 'Commission Per Lot',
    spread_revshare: 'Spread Revshare',
    net_vol_revshare: 'NET Volume Revshare',
    position_vol_revshare: 'Position Vol. Revshare',
    ongoing_net_deposits_revshare: 'Ongoing Net Deposits Revshare',
    ongoing_pl_revshare: 'Ongoing Net PL Revshare',
    ongoing_ngr_revshare_by_country: 'Ongoing NGR Revshare By Country',
    per_position_pl_revshare: 'Per Position PL Revshare',
    minimum_ftd: 'Minumum FTD',
    multiplier: 'Multiplier (%)',
    cap: 'Cap',
    ftd_revshare_cpa: 'FTD Revshare CPA',
    fixed_monthly_commissions: 'Fixed Monthly Commissions',
    flat_monthly_fee: 'Flat Monthly Fee',
    minimum_monthly_guarantee: 'Minimum Monthly Guarantee',
    network_overhead: 'Network Overhead',
    cpa_by_country_and_product: 'CPA by Country & Product',
    ftd_tiers_by_country: 'FTD Tiers By Country',
    cpa_by_instrument_and_country: 'CPA by Instrument and Country',
    'cpa_by_instrument_&_country': 'CPA by Instrument and Country',
    cashback: 'Cashback',
    cpm: 'CPM',
    cpc: 'CPC',
    positionpl: 'PositionPL',
    positionvolume: 'PositionVolume',
    multi_level_symbol_lot_rebate: 'Multi Level Symbol LOT Rebate',
    level: 'Level',
  },
  pixels: {
    pixel_code: 'Pixel Code',
    client_lead_pixel: 'Client Lead Pixel',
    client_registration_pixel: 'Client Registration Pixel',
    client_deposit_pixel: 'Client Deposit Pixel',
    server_lead_pixel: 'Server Lead Pixel',
    server_registration_pixel: 'Server Registration Pixel',
    server_deposit_pixel: 'Server Deposit Pixel',
    server_qcpl_pixel: 'Server QCPL Pixel',
    server_cpaa_pixel: 'Server Qualified CPA Pixel',
    server_cpi_pixel: 'Server CPI Pixel',
    server_commission_pixel: 'Server Commission Pixel',
    no_pixels: 'No pixels are set for this account',
  },
  dashboard: {
    update: 'Update',
    performance: 'Performance',
    top_performing_creatives: 'Top Performing Creatives',
    account_manager: 'Your Account Manager',
    default_link: 'Default Link',
    sub_affiliate_link: 'Sub-Affiliate Link',
    main_title: 'IB Dashboard',
    ref_link: 'Your Referral URL',
    select_brand: 'Select Brand',
    contact_manager: 'Contact Account Manager',
    ref_accounts: 'Referred Accounts',
    transactions: 'Transactions',
    total_deposits: 'Total Deposits',
    first_time_deposits: 'First Time Deposits',
    net_deposits: 'Net Deposits',
    see_full_report: 'See Full Report',
    see_all: 'See All',
    trading_activity: 'Trading Activity',
    positions: 'Positions',
    lot: 'LOT',
    spread: 'Spread',
    closed_positions: 'Closed Positions',
    most_traded_symbols: 'Most Traded Symbols',
    count: 'Count',
    accounts: 'Accounts',
    recently_registered: 'Recently Registered',
    first_time_depositors: 'First Time Depositors',
    account_id: 'Account ID',
    recent_activity: 'Recent Activity',
    transaction_date: 'Transaction Date',
    transaction_id: 'Transaction ID',
    symbol: 'Symbol',
    spread_usd: 'Spread USD',
    open_rate: 'Open Rate',
    close_rate: 'Close Rate',
    pip: 'PIP',
    direction: 'Direction',
    created: 'Created',
  },
  top_bar: {
    logout: 'Logout',
    balance: 'Balance',
    earned: 'Earned',
    adjusted: 'Adjusted',
    paid: 'Paid',
    switch_to_old_version: 'Switch to Old Version',
  },
  sidebar: {
    nav: {
      dashboard: {
        main: 'Dashboard',
      },
      marketing_tools: {
        main: 'Marketing Tools',
        default_links: 'Default Links',
        all: 'All Marketing Tools',
        private: 'Private Marketing Tools',
        affiliate_section_1: 'Carousel Builder',
        affiliate_section_2: 'Search Box Builder',
      },
      reports: {
        main: 'Reports',
        media_report: 'Media Report',
        registrations_report: 'Registrations Report',
        sub_affiliates_report: 'Sub Affiliates Report',
        payments_report: 'Payments Report',
        earnings_report: 'Earnings Report',
        leads_report: 'Leads Report',
        activity_report: 'Activity Report',
      },
      pixels: {
        main: 'Pixels',
        pixels_details: 'Pixels Details',
        pixels_log: 'Pixels Log',
      },
      commission_plan: {
        main: 'Commission Plan',
      },
      account_details: 'Account Details',
      payments: {
        main: 'Payments',
        payments_history: 'Payments History',
        payment_request: 'Payment Request',
      },
      earnings: 'Earnings',
      sub_affiliates: {
        main: 'Sub Affiliates',
        report: 'Sub Affiliates Report',
        links: 'Sub Affiliates Links',
      },
      user_guide: 'Affiliate User Guide',
      affiliate_section: 'Affiliate Iframe section',
    },
  },
  directives: {
    date_range_preconfigured_selector: {
      today: 'Today',
      yesterday: 'Yesterday',
      last_7_days: 'Last 7 Days',
      last_30_days: 'Last 30 Days',
      week_to_date: 'Week to Date',
      month_to_date: 'Month to Date',
      quarter_to_date: 'Quarter to Date',
      year_to_date: 'Year to Date',
      previous_week: 'Previous Week',
      previous_month: 'Previous Month',
      previous_quarter: 'Previous Quarter',
      custom: 'Custom',
    },
    results_per_page_selector: {
      show: 'Show',
      show_n_entries: 'Show {{resultsPerPage}} Entries',
    },
    parameters_generator: {
      dynamic_parameters: 'Dynamic Parameters',
      affiliate_parameters: 'Affiliate Parameters',
      tracking_code: 'Tracking Code',
    },
    tabs: {
      overview: 'Overview',
      transactions: 'Transactions',
      open_trades: 'Open Trades',
      trades: 'Trades',
      bonuses: 'Bonuses',
      commissions: 'Commissions',
    },
  },
  reports: {
    columns: {
      type: 'Type',
      size: 'Size',
      date: 'Date',
      day: 'Day',
      month: 'Month',
      year: 'Year',
      impressions: 'Impressions',
      visitors: 'Visitors',
      leads: 'Leads',
      live_users: 'Live Users',
      demo_users: 'Demo Users',
      ftd: 'FTD',
      qftd: 'QFTD',
      commission: 'Commission',
      commissions: 'Commissions',
      name: 'Name',
      installations: 'Installations',
      tracking_code: 'Tracking Code',
      language: 'Language',
      brand: 'Brand',
      registrations: 'Registrations',
      registration_date: 'Registration Date',
      afp: 'afp',
      country: 'Country',
      status: 'Status',
      source: 'Source',
      first_deposit: 'First Deposit',
      net_deposits: 'Net Deposits',
      user_id: 'User ID',
      total: 'Total',
      earning_date: 'Earning Date',
      amount: 'Amount',
      trader_id: 'Trader ID',
      comission_type: 'Commission Type',
      details: 'Details',
      payment_date: 'Payment Date',
      payment_amount: 'Payment Amount',
      payment_range: 'Payment Range',
      first_deposit_date: 'First Deposit Date',
      pixel_code: 'Pixel Code',
      pixel_type: 'Pixel Type',
      response: 'Response',
      time_stamp: 'Time Stamp',
      affiliate_id: 'Affiliate ID',
      lead_id: 'Lead ID',
      generic1: 'Account ID',
      open_position_date: 'Open Position Date',
      closed_position_date: 'Closed Position Date',
      position_id: 'Position Id',
      volume_usd: 'Volume USD',
      nci: 'NCI',
      deposit_count: '@:terms.deposit_count',
      lot_amount: '@:terms.lot_amount',
      commission_count: '@:terms.commission_count',
      position_count: '@:terms.position_count',
      brokerage_fee: 'Brokerage Fee',
      open_positions: '@:terms.open_positions',
      open_positions_volume: '@:terms.open_position_volume',
      last_open_position_date: '@:terms.last_open_position_date',
      spread: '@:dashboard.spread',
      volume: '@:terms.volume',
      deposits: '@:terms.deposits',
      withdrawals: '@:terms.withdrawals',
      pl: '@:terms.pl',
    },
    controls: {
      to: 'To',
      breakdown_by: 'Breakdown By',
      filter_by: 'Filter By',
      select_all: 'Select All',
      show_details: 'Show Details',
      show_properties: 'Show Properties',
      run_report: 'Run Report',
      search_placeholder: 'Search this table...',
      export_csv: 'Export CSV',
    },
    status_messages: {
      no_results: 'No results found',
      initial: 'Run report to see results...',
    },
    'footer.total': 'Total',
  },
  widgets: {
    top_performing_creatives: {
      title: 'Top Performing Creatives',
      brand: 'Brand',
      name: 'Name',
      registrations: 'Registrations',
      registrations_abbr: 'REG',
      commission: 'Commission',
    },
  },
  marketing_tools: {
    brand: 'Brand',
    type: 'Type',
    language: 'Language',
    name: 'Name',
    size: 'Size',
    filter_by: 'Filter by {{filter}}',
    clear_filters: 'Clear Filters',
    show_creatives: 'Show Creatives',
    filter_creatives: 'Filter Creatives',
    initial_message:
      'Showing 10 most recent creatives. To view all other creatives, select any of the filters above and click "Show Creatives"',
    latest: 'latest',
    oldest: 'oldest',
    creative_name: 'Creative Name',
    click_url: 'Click URL',
    copy_click_url: 'Copy Click URL',
    get_html_code: 'Get HTML Code',
    preview: 'Preview',
    html_code: 'HTML Code',
    copy_code: 'Copy Code',
    download_code: 'Download Code',
    download_image: 'Download Image',
    cancel: 'Cancel',
    find_creative_placeholder: 'Find creative...',
    only_show_brand_message: 'Please contact your affiliate manager if you want to promote this brand',
  },
  pagination: {
    next: 'Next',
    previous: 'Previous',
    showing_x_to_y_of_n_entries: 'Showing {{firstInPage}} to {{lastInPage}} of {{total}} entries',
  },
  account_details: {
    personal_information: 'Personal Information',
    payment_details: 'Payment Details',
    change_password: 'Change Password',
    settings: 'Settings',
    privacy: 'Privacy Policy',
    sources: 'Sources',
    documents: 'Documents',
    personal_fields: {
      first_name: 'First Name',
      last_name: 'Last Name',
      email: 'Email',
      address: 'Address',
      country: 'Country',
      state: 'State',
      city: 'City',
      postcode: 'Postcode',
      phone: 'Phone',
      default_language: 'Default Language',
      site_language: 'Site Language',
      skype: 'Skype',
      telegram: 'Telegram',
      Other_URLS: 'Other URLS',
      website: 'Website',
      main_website_name: 'Main Websitename',
      secondary_website_url: 'Secondary Website URL',
    },
    payment_fields: {
      account_type: 'Account Type',
      payment_currency: 'Payment Currency',
      payment_method: 'Payment Method',
      payment_address: 'Payment Address',
      vat_identification_number: 'VAT Identification Number',
      account_beneficiary: 'Account Beneficiary',
      account_number: 'Account Number',
      bank_name: 'Bank Name',
      bank_branch: 'Bank Branch',
      bank_country: 'Bank Country',
      bank_city: 'Bank City',
      swift_code: 'Swift Code',
      iban_number: 'IBAN Number',
      aba_number: 'ABA Number',
      bank_correspondent: 'Bank Correspondent',
      paypal_email: 'Paypal Email',
      netteller_email: 'Netteller Email',
      netteller_account_number: 'Netteller Account Number',
      skrill_email: 'Skrill Email',
      webmoney_ewallet_number: 'WebMoney E-Wallet Number',
      qiwi_ewallet_number: 'QIWI E-Wallet Number',
      yandex_ewallet_number: 'Yandex E-Wallet Number',
      trading_account_id: 'Trading Account ID',
      payoneer_id: 'Payoneer ID',
      payoneer_username: 'Payoneer Username',
      mybitwallet_email: 'mybitwallet Email',
      ecopayz_account_name: 'ecoPayz Account Name',
      ecopayz_account_number: 'ecoPayz Account Number',
      moneybookers_email: 'Money Bookers Email',
      bitcoin_wallet_address: 'Bitcoin Wallet Address',
    },
    change_password_fields: {
      current_password: 'Current Password',
      new_password: 'New Password',
      confirm_new_password: 'Confirm New Password',
    },
  },
  payments: {
    wire_transfer: 'Wire Transfer',
    paypal: 'PayPal',
    skrill: 'Skrill',
    netteller: 'NetTeller',
    webmoney: 'WebMoney',
    qiwi: 'QIWI',
    yandex: 'Yandex',
    trading_account: 'Trading Account',
    payoneer: 'Payoneer',
    mybitwallet: 'mybitwallet',
    ecopayz: 'ecoPayz',
    moneybookers: 'Money Bookers',
    bitcoin: 'Bitcoin',
  },
  DIALOGS_ERROR: 'Error',
  DIALOGS_ERROR_MSG: 'An unknown error has occurred.',
  DIALOGS_CLOSE: 'Close',
  DIALOGS_PLEASE_WAIT: 'Please Wait',
  DIALOGS_PLEASE_WAIT_ELIPS: 'Please Wait...',
  DIALOGS_PLEASE_WAIT_MSG: 'Waiting on operation to complete.',
  DIALOGS_PERCENT_COMPLETE: '% Complete',
  DIALOGS_NOTIFICATION: 'Notification',
  DIALOGS_NOTIFICATION_MSG: 'Unknown application notification.',
  DIALOGS_CONFIRMATION: 'Confirmation',
  DIALOGS_CONFIRMATION_MSG: 'Confirmation required.',
  DIALOGS_OK: 'OK',
  DIALOGS_YES: 'Yes',
  DIALOGS_NO: 'No',
  do_not_show_again: 'Do not show again',
  i_agree: 'I Agree',
  i_have_read_understood: 'I have read, understood and agree to be bound by the above attached documents',
  notifications: {
    account_details: {
      update_success: 'Details updated successfully',
      update_error: 'Error saving details',
      password_change_success: 'Password updated successfully',
      password_change_error: 'Error saving password',
      get_user_contact_error: 'User Contact Info is Missing',
    },
    copied_to_clipboard: 'Copied to clipboard',
    uploads: {
      success: 'Upload success',
      error: 'Error uploading',
    },
    payment_requests: {
      request_success: 'Payment request was sent successfully',
      request_error: 'Error while creating the payment request',
      no_payment_selected: 'To make a payment request you need to select a payment method.',
      missing_details: 'To make a payment request please fill out your payment details.',
      select_payment: 'Select Payment Method',
      eligible_for_payment_title: 'Eligible For Payment',
      eligible_for_payment_message_p1: 'You are eligible for payment of ',
      eligible_for_payment_message_p2: 'for commissions generated until ',
      non_eligible_for_payment_title: 'Non Eligible For Payment',
      non_eligible_for_payment_message: "Your current outstanding balance doesn't meet the payment threshold",
    },
    chargeback: {
      success: 'Commission Changes Successfully',
      error: 'Commission Change Failed',
    },
  },
  gdpr: {
    disclaimer:
      'Please note that due to data protection regulation changing within the European Union, we have had to make some changes to our terms and conditions. Please review the changes and confirm your acceptance of the updated terms. You may withdraw your acceptance at any time, however this may result in your use of the system being withdrawn or restricted.',
    terms_and_conditions: 'Terms and Conditions',
    privacy_policy: 'Privacy Policy',
    marketing_agreement: 'I agree to receive promotional material',
    agreement_span: 'I agree to the ',
    terms_tooltip:
      'Check here to indicate that you have read and agree to our Terms and Conditions, You may withdraw your consent at any time.',
    privacy_tooltip:
      'Check here to indicate that you have read and agree to our Privacy Policy, You may withdraw your consent at any time.',
    marketing_tooltip:
      'Check here to indicate that you agree to receive marketing and promotional material, You may withdraw your consent at any time.',
  },
};
